### ISSUE TITLE
Can't mine blocks with pickaxes ver 0.14.5 1.20.1 forge

### ISSUE THREAD

**Issue by Ilya-torshov** [cassiancc/Pyrite#4]
See modlist below. Issue appeared when adding pyrite, dissapeared when removing it.

![image](https://github.com/user-attachments/assets/495155a1-c1ab-47be-87ee-562f3bc3e640)

**Comment by cassiancc** [comment]
Fixed in 0.14.6, thanks for reporting!

**Comment by Ilya-torshov** [comment]
ah nice, good to hear! Any idea when it will be released? Cheers

**Comment by cassiancc** [comment]
Already out on Modrinth, awaiting approval on CurseForge.

**Comment by Ilya-torshov** [comment]
Hm, I can not find it on modrinth

**Comment by cassiancc** [comment]
https://modrinth.com/mod/pyrite/version/0.14.6+1.20.1
